CREATE TABLE IF NOT EXISTS todo (
  id         INT  PRIMARY KEY AUTO_INCREMENT,
  content    VARCHAR(500),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
  id       INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email    VARCHAR(100) NOT NULL UNIQUE,
  username VARCHAR(50)  NOT NULL UNIQUE,
  password VARCHAR(60)  NOT NULL,
  role     VARCHAR(20)  NOT NULL
);
